[[data]]
gotra = "kaashyapa"
pravara = ["kaashyapa", "aavatsaara", "naidruva"]
suutra = "ashvalayana"
veda_shaakhaas = ["rigveda/sakala"]
ancestral_districts = ["dakshina kannada"]
paternal_jaati = "shivalli tulu brahmin"
id = "kaashyapa/KA/south_west/kaashyapa/manyu"
paternal_haplogroup = "R-Y6"
maternal_haplogroup = "R30a"
data_provider = "23andme"
